# Randomly selecting tweets for Hydration
July 20, 2022

This notebook first imports the no_retweets_set_filtered.tsv file which contains all of the non-retweet data from the Pancaea Lab, version 120 which was uploaded on June 26, 2022 (https://zenodo.org/record/6758164) 

This notebook will randomize the tweets and created "batches" for hydration. 

We will remove the following, already hydrated tweets: 

1. 120,000 tweets that Anish M. already randomly selected 120,000 ("data/test.txt")
2. 1,000,000 tweets that Anish M. randomly selected ("data/1_million_tweets.txt")
3. 10,000,000 tweets Meghan H. randomly selected ("data/10_million_tweets.txt")

This list of tweets will then be hydrated to support PASC tweet topic modeling project

In [1]:
import os

import pandas as pd
import numpy as np
import random
import matplotlib

**Import full twitter dataset from Panacea**

In [2]:
tweets = pd.read_csv("../data/no_retweets_set_filtered.tsv", delimiter = '\t')

In [3]:
len(tweets)

190561814

**Remove duplicate tweets**

In [4]:
tweets = tweets.drop_duplicates()
print(len(tweets))

190538594

**Import previously hydrated tweets**

In [5]:
first_set  = pd.read_csv("../data/test.txt")
second_set = pd.read_csv("../data/1_million_tweets.txt")
third_set = pd.read_csv("../data/10_million_tweets.txt")

**Create list**

In [22]:
first_set_list = first_set['tweet_id'].reset_index(drop = True)
second_set_list = second_set['tweet_id'].reset_index(drop = True)
third_set_list = third_set['tweet_id'].reset_index(drop = True)

In [23]:
hydrated_tweet_sets = [first_set_list, second_set_list, third_set_list]
hydrated_tweet_lists = pd.concat(hydrated_tweet_sets)

In [24]:
print(len(hydrated_tweet_lists))

11120000

In [25]:
hydrated_tweet_lists

0          1220749184489476096
1          1221488900348055552
2          1221828612443267074
3          1221829107194814465
4          1221835146652876800
                  ...
9999995    1496389288879177728
9999996    1291413793910775808
9999997    1234766456144793600
9999998    1476795986261393409
9999999    1268644385861894145
Name: tweet_id, Length: 11120000, dtype: int64

**Remove hydrated tweets from the larger dataset**

In [41]:
print(len(tweets))
tweets = tweets[~tweets.tweet_id.isin(hydrated_tweet_lists)]
print(len(tweets))

190538594
179418594

**Randomly shuffle tweets**

In [42]:
random.seed(720)
random_sample_tweets = random.sample(range(len(tweets['tweet_id'])), len(tweets['tweet_id']))

In [43]:
random_sample_tweets

[41723394,
 3406980,
 51801891,
 118475004,
 123831248,
 22656462,
 126810388,
 8747814,
 162953142,
 120602893,
 165386652,
 113647818,
 80127383,
 80817300,
 82127867,
 96421427,
 83853952,
 117648053,
 66440728,
 98432074,
 79667770,
 134049205,
 123412295,
 141058384,
 67789482,
 117473258,
 3648367,
 44347414,
 43068064,
 167842185,
 125443550,
 120255284,
 66815943,
 149409149,
 154131123,
 41662710,
 85363606,
 102012596,
 75623676,
 66340766,
 110611512,
 142334139,
 82975778,
 81372041,
 12656441,
 21707497,
 54632638,
 25781273,
 54684534,
 78756418,
 128443299,
 162687619,
 178703232,
 112311363,
 99342069,
 161520670,
 157960651,
 147896077,
 170540797,
 33952995,
 161636435,
 29425743,
 127208881,
 38327403,
 29826311,
 123110542,
 14815617,
 81490103,
 94010315,
 67195955,
 29896940,
 111414066,
 141844697,
 13585672,
 115263988,
 61295835,
 77213431,
 76354550,
 124584444,
 75129599,
 62591359,
 24510512,
 76559343,
 17640092,
 52102939,
 83517366,
 37462668,
 54491975,
 13765654,
 21974009,
 71107799,
 94624247,
 156853901,
 155704537,
 38981539,
 173409188,
 41631153,
 52371594,
 86927379,
 16012308,
 12943797,
 62833928,
 49443001,
 28992078,
 21225177,
 73468586,
 50006731,
 102612100,
 85245835,
 110274059,
 102177076,
 93361614,
 15392322,
 58256257,
 6558928,
 2341273,
 126466407,
 99207491,
 22828897,
 52790778,
 134324339,
 29402615,
 26923141,
 174355297,
 138274465,
 159665114,
 93507642,
 126172952,
 156958510,
 27222995,
 59659421,
 137790063,
 83958242,
 25697343,
 7539369,
 28851260,
 126259702,
 170465668,
 23872235,
 87005623,
 145309410,
 96085414,
 30084646,
 70559203,
 114529790,
 17591547,
 149873710,
 61688484,
 78699966,
 161327118,
 176008271,
 121504256,
 33312707,
 40999755,
 119233058,
 172654996,
 29278998,
 103608656,
 142286570,
 68936247,
 94429824,
 130700368,
 175835297,
 138962142,
 34697745,
 46876150,
 120560825,
 156437385,
 146749659,
 12567291,
 76940361,
 15214977,
 38131835,
 43821025,
 174643100,
 122095346,
 153848213,
 41039873,
 3092479,
 76216283,
 1927871,
 41207940,
 55057164,
 141890203,
 110729522,
 7320037,
 51473298,
 23131225,
 114850471,
 85943650,
 142510404,
 108150771,
 138868617,
 31519660,
 156553189,
 152646531,
 138601533,
 75611361,
 107762440,
 49711894,
 91106903,
 80556407,
 141400852,
 169864130,
 54421562,
 144435432,
 20493677,
 86027530,
 41690860,
 16615183,
 37042286,
 110489463,
 21505570,
 91503957,
 69104560,
 81772692,
 47256832,
 1988760,
 134338815,
 144216963,
 130114575,
 68125005,
 173459605,
 103285382,
 29037282,
 82068923,
 107843133,
 65515677,
 75864938,
 161102917,
 169687728,
 162851134,
 126347157,
 63498981,
 73452103,
 159893623,
 76492682,
 33733531,
 14454698,
 161102254,
 135330878,
 170997124,
 104737242,
 71610523,
 23837171,
 149481678,
 37359156,
 85465049,
 28634809,
 96902104,
 154896010,
 110332134,
 40902154,
 21858666,
 10998040,
 1798325,
 8820946,
 106122384,
 143770068,
 84677954,
 53863890,
 99905528,
 28496497,
 50507444,
 129526332,
 86441739,
 114513394,
 42488954,
 56745978,
 174325080,
 113666480,
 129233213,
 125019458,
 106839547,
 120719261,
 124028119,
 142082948,
 130038370,
 91392412,
 19492804,
 2630721,
 53176709,
 165929657,
 160358176,
 118123258,
 39015202,
 138692002,
 143950907,
 67885037,
 65892240,
 32264739,
 84061701,
 145242138,
 2274553,
 61656949,
 85665763,
 52342321,
 32944266,
 4680017,
 46242661,
 132528708,
 60769137,
 49129865,
 38050883,
 50468358,
 132317953,
 27216606,
 80535260,
 3574363,
 134629409,
 15753016,
 12690354,
 14444095,
 133889373,
 67364267,
 138839408,
 68775813,
 108741584,
 162369936,
 143549895,
 34805388,
 26804156,
 109346780,
 58768879,
 49524363,
 38632992,
 98887021,
 128442503,
 134638313,
 99405674,
 75767845,
 143888258,
 98140952,
 40065689,
 76517074,
 110833399,
 80991731,
 133929665,
 170097963,
 62551262,
 87838993,
 159180670,
 29704456,
 123025312,
 111749169,
 26837448,
 9545736,
 137265960,
 38576500,
 57936900,
 136116333,
 45437349,
 30253771,
 107144947,
 139221680,
 127199833,
 114654283,
 100710342,
 20994865,
 13240826,
 820583,
 87515074,
 92476551,
 11293895,
 153598201,
 2138515,
 84043393,
 20021890,
 80928026,
 28604081,
 34498998,
 31222227,
 151166630,
 76700598,
 30748653,
 40126979,
 3596609,
 41708215,
 124523031,
 151059246,
 83629421,
 97381408,
 56706965,
 145228939,
 35467216,
 135605095,
 55353386,
 166548363,
 7537594,
 131332345,
 94821398,
 90017786,
 115617493,
 123693776,
 51651280,
 65370174,
 68830533,
 79937674,
 61551406,
 146339215,
 168496544,
 56552676,
 85683654,
 6061621,
 19358500,
 52687598,
 115032296,
 46468335,
 127611939,
 52740835,
 164682369,
 115655910,
 12303689,
 124390770,
 34152092,
 169844666,
 12328899,
 26515178,
 172038736,
 93709790,
 140874231,
 119309967,
 33288186,
 65352375,
 22390984,
 45852459,
 88478661,
 92769801,
 158293861,
 152628835,
 143675090,
 106642952,
 178012821,
 31369065,
 178515083,
 96408242,
 134250516,
 66375945,
 36126643,
 83197287,
 107349995,
 169278007,
 112709179,
 1571435,
 92670364,
 51737049,
 115582980,
 169520395,
 165763733,
 83918849,
 131107340,
 175456459,
 40958484,
 62563316,
 140972926,
 72775367,
 128701753,
 80518158,
 19226055,
 131141449,
 94617490,
 154370753,
 144641823,
 49030522,
 14326044,
 2572708,
 74794616,
 82729603,
 151290846,
 122901272,
 21443462,
 119865789,
 11938638,
 94164559,
 132901662,
 48526356,
 14432322,
 106439459,
 71602481,
 13864,
 24087070,
 50823646,
 6697884,
 46220661,
 177020334,
 18568390,
 150301528,
 84561467,
 45557381,
 129451553,
 152163441,
 49190501,
 94000394,
 869632,
 89275944,
 133643140,
 128311007,
 161242135,
 108999060,
 64708685,
 87221502,
 147683697,
 65923693,
 96107804,
 126066468,
 59915455,
 148438511,
 76588990,
 149926802,
 8270777,
 55263577,
 83474704,
 47382739,
 148088158,
 113648973,
 165266867,
 145467664,
 167112024,
 125364900,
 165381610,
 105264255,
 12580409,
 50074335,
 148221288,
 166118846,
 94722488,
 12790394,
 13124261,
 164356436,
 156064625,
 161551308,
 127460805,
 97129683,
 142377184,
 61543926,
 177674353,
 8570391,
 143678243,
 53959841,
 41474707,
 86341303,
 47262366,
 36101449,
 18585189,
 26194657,
 37410078,
 92144155,
 94024058,
 7953920,
 84583889,
 172950530,
 45830801,
 107383304,
 44660459,
 129144551,
 126769654,
 73537140,
 7241454,
 9137636,
 97239027,
 92017391,
 69380708,
 141181002,
 103347128,
 95099654,
 110737051,
 101102886,
 31398074,
 96000918,
 75833288,
 18522728,
 145540846,
 48817811,
 173282034,
 170821904,
 9767107,
 53775654,
 45121564,
 38174848,
 162964765,
 112109894,
 153299067,
 15990968,
 67164720,
 56453559,
 155293222,
 113717959,
 108752583,
 122424891,
 174724796,
 166370701,
 174965885,
 164783074,
 99778939,
 124382827,
 28019956,
 153570885,
 174596716,
 57705886,
 52329364,
 51494812,
 132009969,
 141601845,
 119055646,
 153484608,
 164400668,
 132580396,
 128929678,
 115942498,
 148743769,
 115640854,
 135732841,
 25985475,
 170496664,
 67501448,
 18612098,
 117660825,
 165649937,
 110028095,
 70861247,
 68703244,
 155449257,
 109739276,
 157301180,
 50273101,
 79971739,
 163463361,
 40086682,
 141900751,
 136402193,
 4890931,
 151980871,
 151648710,
 86702759,
 137832632,
 2901709,
 151809606,
 97874118,
 1896463,
 133084634,
 159829447,
 5552760,
 40817500,
 10879803,
 110486254,
 142469341,
 98213860,
 175080086,
 78007579,
 152493794,
 45434269,
 137877124,
 129776455,
 26775879,
 149286039,
 49071570,
 47556001,
 128422037,
 13421945,
 127002293,
 60596257,
 164978073,
 61603635,
 142100829,
 157670160,
 56955389,
 138042955,
 23599514,
 85704061,
 2998690,
 24426100,
 35907184,
 8632080,
 94805491,
 114098773,
 125607098,
 107265911,
 155130328,
 112692145,
 12471229,
 125644524,
 118357438,
 169176930,
 157098094,
 95940292,
 34040087,
 72040687,
 137917671,
 14068790,
 160642453,
 86296181,
 114731140,
 94309035,
 3814570,
 148823031,
 87515467,
 64476195,
 157017545,
 65986427,
 103353987,
 81894657,
 91529609,
 39194695,
 119292727,
 59506567,
 121242250,
 7984523,
 92247674,
 18179038,
 80315453,
 41610776,
 12595717,
 107552104,
 37219049,
 165817853,
 137119341,
 134126819,
 162484107,
 32449162,
 165769753,
 105285545,
 25482350,
 99859314,
 132774265,
 144002646,
 137740873,
 133813956,
 133059263,
 90355641,
 138690503,
 46392072,
 174459084,
 122790970,
 881172,
 128368730,
 69616975,
 12386940,
 55294043,
 133475776,
 14313429,
 115215087,
 116727835,
 21826752,
 72935573,
 122617063,
 96181192,
 160507100,
 31605658,
 78339778,
 40262731,
 153260447,
 134858596,
 27392336,
 41127966,
 7384105,
 131955290,
 1765632,
 70496887,
 85826280,
 101564612,
 49397488,
 98127470,
 147195899,
 144721298,
 65592590,
 160435875,
 34569899,
 74152792,
 113324514,
 4107469,
 127288959,
 44652401,
 86536631,
 138590133,
 46472098,
 82393952,
 149569237,
 154862634,
 102879685,
 63565003,
 142719726,
 84118422,
 154820496,
 84731543,
 41227439,
 132668572,
 87496785,
 158317936,
 112858074,
 114398461,
 126952488,
 33892590,
 35479058,
 132293431,
 100451845,
 70372405,
 172363009,
 17274641,
 104887444,
 147733141,
 28249947,
 61644230,
 167493162,
 131272967,
 71362564,
 46517675,
 91566788,
 48313439,
 116335457,
 161416375,
 38563795,
 106402132,
 167648921,
 137601730,
 77010283,
 139566614,
 29865180,
 9179007,
 172485411,
 73867863,
 86059431,
 113433230,
 136107432,
 107910493,
 101141009,
 67682738,
 119606797,
 120027562,
 46666625,
 43006321,
 31514824,
 93457457,
 81676144,
 116368445,
 88931408,
 35225017,
 136754041,
 74307156,
 30972480,
 30050858,
 92766443,
 43086578,
 19771412,
 130160182,
 146272419,
 138484363,
 142419016,
 81594320,
 119654780,
 70174511,
 99298388,
 168407300,
 74189544,
 25304100,
 174916387,
 121538729,
 89797070,
 61152586,
 158962210,
 82755862,
 45482867,
 162638279,
 114748481,
 27269618,
 3446973,
 47275007,
 125848743,
 57719536,
 157403882,
 36696534,
 36613371,
 27865128,
 45323689,
 144740020,
 148030858,
 63116616,
 121213634,
 145297780,
 105731727,
 75781152,
 129045433,
 65327283,
 122874865,
 81057866,
 1832428,
 155863110,
 120076756,
 82333687,
 4257070,
 163579804,
 131937034,
 149554805,
 145649299,
 115888358,
 83794947,
 87941088,
 109980570,
 66587734,
 122027455,
 14115868,
 156904628,
 111498805,
 85919949,
 124340897,
 131438118,
 62283954,
 115542912,
 174657824,
 166233250,
 145317881,
 109234541,
 91036369,
 61806442,
 8908766,
 13131349,
 106323146,
 126408033,
 107755585,
 16563724,
 5585884,
 88435682,
 101877414,
 105927732,
 146158785,
 56187748,
 81722972,
 178886969,
 128029908,
 82347313,
 137235002,
 110336433,
 90527259,
 164386408,
 55867020,
 104389806,
 154135306,
 103432961,
 164549910,
 47245455,
 145893550,
 161584699,
 13343585,
 134001381,
 115854425,
 105459324,
 51826097,
 149663681,
 34636534,
 173254790,
 86714925,
 152220467,
 154823644,
 70620458,
 45258028,
 47408461,
 19922276,
 137426585,
 86386185,
 155761224,
 77076002,
 158548395,
 113795508,
 143516163,
 65160654,
 85522857,
 43097680,
 102614975,
 117527190,
 153929445,
 86843333,
 107507159,
 59748002,
 45965872,
 79193908,
 169043232,
 101519538,
 95737991,
 53923224,
 44330424,
 45103180,
 70983295,
 129467600,
 53977262,
 170831751,
 155920661,
 33379187,
 23262196,
 40895267,
 170921505,
 136780312,
 88656727,
 23877214,
 126062029,
 81840584,
 98969770,
 113202260,
 138430942,
 117173719,
 132563933,
 101827864,
 ...]

In [44]:
len(random_sample_tweets)

179418594

**Retrieve the tweets from the index**

In [45]:
shuffled_tweets = tweets.iloc[random_sample_tweets]
print(len(shuffled_tweets))

179418594

In [46]:
shuffled_tweets[['tweet_id']].drop_duplicates()

                      tweet_id
44308260   1263073429974126592
3618155    1233405731690422272
55010391   1271172600765583361
125814948  1344390385360113669
131503092  1353241437375229952
...                        ...
175839463  1463761788932141061
49446277   1266466856447152135
34737125   1257270480052109313
111630456  1327069251421745152
74226556   1286334218352627719

[179418594 rows x 1 columns]

**Save dataset**

In [60]:
shuffled_tweet_ids = shuffled_tweets['tweet_id']

In [61]:
for id, df_i in  enumerate(np.array_split(shuffled_tweet_ids, 4)):
    df_i.to_csv('../data/tweets_to_hydrate_{id}.txt'.format(id=id))